[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
ETHectiveEvm = "https://k8s.testnet.json-rpc.ETHective.network/"
